.TH SUNCOIN-CLI "1" "June 2016" "suncoin-cli 0.12"
.SH NAME
suncoin-cli \- a remote procedure call client for SunCoin Core. 
.SH SYNOPSIS
suncoin-cli [options] <command> [params] \- Send command to SunCoin Core. 
.TP
suncoin-cli [options] help \- Asks SunCoin Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the suncoin-cli program. suncoin-cli is an RPC client used to send commands to SunCoin Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBsuncoind\fP, \fBsuncoin.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
